#%RAML 1.0 Trait

responses:
  400:
    body:
      application/json:
        type: object
        properties:
          message: string
        example: |
          {"message": "Bad request"}

  404:
    body:
      application/json:
        type: object
        properties:
          message: string
        example: |
          {"message": "Resource not found"}

  405:
    body:
      application/json:
        type: object
        properties:
          message: string
        example: |
          {"message": "Method not allowed"}
  
  406:
    body:
      application/json:
        type: object
        properties:
          message: string
        example: |
          {"message": "Not acceptable"}
  
  415:
    body:
      application/json:
        type: object
        properties:
          message: string
        example: |
          {"message": "Unsupported media type"}  

  501:
    body:
      application/json:
        type: object
        properties:
          message: string
        example: |
          {"message": "Not Implemented"}