#%RAML 1.0
title: brisa-core-niugis-exp

baseUri: http://{domain}/api

uses:
  security: exchange_modules/f36688ab-93de-44ae-966d-9cb7c3d1cfa5/security-library/1.0.0/security-library.raml

traits:
  common-responses: !include exchange_modules/f36688ab-93de-44ae-966d-9cb7c3d1cfa5/common-responses/1.0.0/common-responses.raml
  health: !include exchange_modules/f36688ab-93de-44ae-966d-9cb7c3d1cfa5/health-check/1.0.0/health-check.raml

/v1:
  /services:
    get:
      securedBy: [security.basicAuth]
      description: "This is a location and an aggregator of existing building assets in a given Service Area. It aggregates all the existing buildings in a Service Area, providing information on: 1) their reversion status; 2) the different areas of responsibility (BCR/BAS, Petrol Stores, Fastfood, Hotel units and Auto Workshops); 3) Services provided and 4) Floor plans defining the areas of responsibility of BCR/BAS and Petrol Stores."
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "services": []
                }  
    /{id}:
      get:
        securedBy: [security.basicAuth]
        description: for one service info as 1) their reversion status; 2) the different areas of responsibility (BCR/BAS, Petrol Stores, Fastfood, Hotel units and Auto Workshops); 3) Services provided and 4) Floor plans defining the areas of responsibility of BCR/BAS and Petrol Stores."
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                  "service": []
                  }         
  /highways:
    get:
      securedBy: [security.basicAuth]
      description: Highways Brisa list
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "highways": []
                }  
    /{id}:
      get:
        securedBy: [security.basicAuth]
        description: One selected highway by Id
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                  "highway": []
                  }        
  /tolls:
    get:
      securedBy: [security.basicAuth]
      description: "It is a location and an aggregating element. It brings together all the structures and pedestrian circulation areas that form part of or border a main or connecting road and are an integral part of a Toll Plaza. They include the roof structure (Toll Plaza), Islands and Lanes and the Service Tunnel (when present). Also excluded are associated or independent structures such as pedestrian crossings, which belong to the Works of Art asset class."
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "pedestrians": []
                }  
    /{id}:
      get:
        securedBy: [security.basicAuth]
        description: One selected pedestrian by Id
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                  "highway": []
                  }    
  /nodes:
    get:
      securedBy: [security.basicAuth]
      description: Nodes Brisa features
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "nodes": []
                }
    /{id}:
      get:
        securedBy: [security.basicAuth]
        description: One selected highway by Id
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                  "node feature": []
                  }          
    /modeling:
     get:
      securedBy: [security.basicAuth]
      description: "Node Branch Metadata"
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "node modeligns": []
                }  
     /{id}:
        get:
          securedBy: [security.basicAuth]
          description: One selected pedestrian by Id
          responses:
            200:
              body:
                application/json:
                  example: |
                    {
                      "node modeling feature": []
                    } 
  /underlines:
    get:
      securedBy: [security.basicAuth]
      description: "Underlines features"
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "Underline features": []
                }  
    /{id}:
      get:
        securedBy: [security.basicAuth]
        description: One selected pedestrian by Id
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                  "underline": []
                  }    
  /bcr:
    get:
      securedBy: [security.basicAuth]
      description: bcr features
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "bcr features": []
                }  
    /{id}:
      get:
        securedBy: [security.basicAuth]
        description: One feature
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                  "bcr feature": []
                  }             




